import firstImage from "../assets/images/screens/screen1.png";
import secondImage from "../assets/images/screens/screen2.png";
import thirdImage from "../assets/images/screens/screen3.png";
import fourthImage from "../assets/images/screens/screen4.png";
import fifthImage from "../assets/images/screens/screen5.png";
import sixthImage from "../assets/images/screens/screen6.png";
import seventhImage from "../assets/images/screens/screen7.png";
import realMadrid from "../assets/images/Real Madrid.png";

export const markData = [
  {
    name: "Alvarez Denis",
    mark: 3,
    hasEye: false,
    isSelected: false,
  },
  {
    name: "Bacarisa Adrian",
    mark: 2,
    hasEye: false,
    isSelected: false,
  },
  {
    name: "Canepz Patrick",
    mark: 2,
    hasEye: false,
    isSelected: false,
  },
  {
    name: "Grech Paul",
    mark: 2,
    hasEye: true,
    isSelected: false,
  },
  {
    name: "Barcelo Jason",
    mark: 3,
    hasEye: false,
    isSelected: true,
  },
  {
    name: "Macias Michael",
    mark: 2,
    hasEye: false,
    isSelected: true,
  },
];

export const data = [
  {
    title: "Playing the ball first",
    first: "Yes",
    second: "",
    third: "No",
    hasColor: [],
  },
  {
    title: "Studs used",
    first: "No",
    second: "",
    third: "Yes",
    hasColor: [3],
  },
  {
    title: "Intensity",
    first: "Low",
    second: "Moderate",
    third: "High",
    hasColor: [3],
  },
  {
    title: "Points of contact",
    first: "Foot",
    second: "Ankle",
    third: "High",
    hasColor: [1],
  },
  {
    title: "Type of contact",
    first: "Slight",
    second: "Glancing",
    third: "Full",
    hasColor: [2],
  },
  {
    title: "Towards the opponent",
    first: "No",
    second: "Partially",
    third: "Direct",
    hasColor: [3],
  },
];

export const offenderData = [
  {
    title: "Initiating the contact",
    first: "Pulled",
    second: "Bent",
    third: "Straight",
    hasColor: [],
  },
  {
    title: "Straight leg",
    first: "",
    second: "",
    third: "Yes",
    hasColor: [],
  },
  {
    title: "Lunge/jump",
    first: "",
    second: "",
    third: "Yes",
    hasColor: [3],
  },
  {
    title: "From behind",
    first: "Yes",
    second: "Debatable",
    third: "No",
    hasColor: [3],
  },
  {
    title: "Attempt to play the ball",
    first: "Yes",
    second: "Debatable",
    third: "No",
    hasColor: [],
  },
];

export const opponentData = [
  {
    title: "Result/consequence",
    first: "Light",
    second: "Moderate",
    third: "Serious",
    hasColor: [],
  },
  {
    title: "Leg supporting body",
    first: "No",
    second: "Partially",
    third: "Fully",
    hasColor: [1],
  },
  {
    title: "Contact to head/neck",
    first: "",
    second: "",
    third: "Yes",
    hasColor: [],
  },
  {
    title: "Opponent saves himself",
    first: "",
    second: "",
    third: "Yes",
    hasColor: [3],
  },
];

export const incidentData = [
  {
    hadCard: true,
    minute: 73,
    time: "9:34",
    tSubtopic: ["Ball out of play", "Pushing/pulling"],
    Offender: ["Rolon", "Real Madrid", "Trans"],
    DBR: "warning",
    officialMark: 4,
    hasMessage: false,
    communityMark: ["4.1"],
    aa: 4,
    hk: 4,
    ko: 4,
    bgColor: "bg-white",
  },
  {
    hadCard: false,
    minute: null,
    time: "",
    tSubtopic: ["Ball out of play", "Pushing/pulling"],
    Offender: ["Dömov", "barcelona", "Kuressaare"],
    DBR: "warning",
    officialMark: 5,
    hasMessage: false,
    communityMark: ["4.5"],
    aa: 4,
    hk: 5,
    ko: 4,
    bgColor: "bg-white",
  },
  {
    hadCard: true,
    minute: 90,
    time: "12:06",
    tSubtopic: ["Severity", "Studs directed high"],
    Offender: ["Kukhianidze", "Real Madrid", "Trans"],
    DBR: "play",
    officialMark: 4,
    hasMessage: true,
    communityMark: ["2.8", "0.0"],
    aa: 2,
    hk: 4,
    ko: 3,
    bgColor: "bg-[#b4d8bc]",
  },
  {
    hadCard: false,
    minute: null,
    time: "",
    tSubtopic: ["2nd yellow", "Reckless"],
    Offender: ["Kukhianidze", "Real Madrid", "Trans"],
    DBR: "play",
    officialMark: 3,
    hasMessage: true,
    communityMark: ["2.0"],
    aa: 1,
    hk: 3,
    ko: 2,
    bgColor: "bg-[#a3cfab]",
  },
];

export const officialData = [
  {
    firstNum: 1,
    statusSecondNum: true,
    secondNum: 2,
    title: "Alev Ain",
    comment: "",
    hasEye: false,
    isSelected: false,
  },
  {
    firstNum: 3,
    statusSecondNum: true,
    secondNum: 4,
    title: "Kaasik Hannes",
    comment:
      "Samasel viisil olukorda minek on vastase suhtes hoolimatu. Teisest kollasest kaardist paästab tösisema kontakti puudumine.",
    hasEye: false,
    isSelected: false,
  },
  {
    firstNum: 2,
    statusSecondNum: true,
    secondNum: 3,
    title: "Öismaa Kaupo",
    comment: "",
    hasEye: true,
    isSelected: false,
  },
  {
    firstNum: 1,
    statusSecondNum: true,
    secondNum: 2,
    title: "Maalinn Rasmus",
    comment: "",
    hasEye: false,
    isSelected: true,
  },
  {
    firstNum: 1,
    statusSecondNum: false,
    secondNum: 2,
    title: "Lukk Kristjan",
    comment: "",
    hasEye: false,
    isSelected: true,
  },
  {
    firstNum: 2,
    statusSecondNum: false,
    secondNum: 2,
    title: "Mikson Maikel",
    comment: "tulemust ei paista- muidu act by itself igati hoiatusväärne",
    hasEye: false,
    isSelected: true,
  },
  {
    firstNum: 3,
    statusSecondNum: false,
    secondNum: 4,
    title: "Jakobson Jagnar",
    comment:
      "Selgelt hiljaks jäämine ja kung-fu löök. Önneks läheb see peopessa ja suuremat tagajärge pole.",
    hasEye: false,
    isSelected: true,
  },
];

export const learningPointData = [
  {
    minute: null,
    time: "1:13",
    tSubtopic: ["Offence", "Tackle"],
    Offender: ["", "Barcelona", "Kuressaare"],
    DBR: "whistle",
    officialMark: ["2", "bg-gradient-to-r from-white to-[#baf6ff]", "big"],
    hasMessage: false,
    communityMark: "2",
    aa: "2",
    hk: "2",
    ko: "4",
  },
  {
    minute: null,
    time: "1:44",
    tSubtopic: ["Management", "Delaying the flag"],
    Offender: ["", "", ""],
    DBR: "flag",
    officialMark: ["+", "bg-[#6ecb01]", "small"],
    hasMessage: false,
    communityMark: "2.0",
    aa: "+",
    hk: "+",
    ko: "+",
  },
  {
    minute: null,
    time: "2:50",
    tSubtopic: ["Management", "Delaying the flag"],
    Offender: ["", "", ""],
    DBR: "speakingHead",
    officialMark: ["+", "bg-[#6ecb01]", "big"],
    hasMessage: true,
    communityMark: "1.8",
    aa: "+",
    hk: "+",
    ko: "+/-",
  },
  {
    minute: null,
    time: "5:40",
    tSubtopic: ["Severity", "Strike / push"],
    Offender: ["Rolon", "Real Madrid", "Trans"],
    DBR: "speakingBody",
    officialMark: ["2", "bg-gradient-to-r from-[#e6e6e7] to-[#ceca23]", "big"],
    hasMessage: false,
    communityMark: "2.8",
    aa: "3",
    hk: "2",
    ko: "3",
  },
  {
    minute: 40,
    time: "6:31",
    tSubtopic: ["Dissent & misconduct", "Serveral issues"],
    Offender: ["Kukhianidze", "Real Madrid", "Trans"],
    DBR: "yellowCard",
    officialMark: ["4", "bg-[#ffff00]", "small"],
    hasMessage: false,
    communityMark: "3.9",
    aa: "4",
    hk: "4",
    ko: "4",
  },
  {
    minute: 63,
    time: "6:31",
    tSubtopic: ["Stopping an attack", "Midfield"],
    Offender: ["Suvinömm", "Barcelona", "Kuressaare"],
    DBR: "yellowCard",
    officialMark: ["4", "bg-[#ffff00]", "small"],
    hasMessage: false,
    communityMark: "4.9",
    aa: "4",
    hk: "4",
    ko: "4",
  },
];

export const refereeData = [
  {
    minute: null,
    time: "2:12",
    tSubtopic: ["Offside", "Moment of play"],
    Offender: ["", "Real Madrid", "Trans"],
    DBR: "play",
    officialMark: ["2", "bg-gradient-to-r from-white to-[#bbf6fe]", "small"],
    hasMessage: false,
    communityMark: "2.4",
    aa: "2",
    hk: "2",
    ko: "3",
  },
  {
    minute: null,
    time: "11:17",
    tSubtopic: ["Offside", "Moment of play"],
    Offender: ["", "Real Madrid", "Trans"],
    DBR: "play",
    officialMark: ["4", "bg-[#44cbe1]", "small"],
    hasMessage: false,
    communityMark: "3.7",
    aa: "4",
    hk: "4",
    ko: "4",
  },
];

export const pagiNationData = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];

export const screenData = [
  {
    screenUrl: firstImage,
    date: "06.10.24",
    teamAvatarUrl: realMadrid,
    teamName: "Kuressaare",
    member: "Volossatov",
    hasComment: false,
    num: "4",
  },
  {
    screenUrl: secondImage,
    date: "21.09.24",
    teamAvatarUrl: realMadrid,
    teamName: "Tammeka",
    num: "4",
    hasComment: true,
    member: "Epton",
  },
  {
    screenUrl: thirdImage,
    date: "15.09.24",
    teamAvatarUrl: realMadrid,
    teamName: "Kalju",
    num: "4",
    hasComment: false,
    member: "Patrikejevs",
  },
  {
    screenUrl: fourthImage,
    date: "13.09.24",
    teamAvatarUrl: realMadrid,
    teamName: "Tammeka",
    num: "4",
    hasComment: true,
    member: "Pedmanson",
  },
  {
    screenUrl: fifthImage,
    date: "01.09.24",
    teamAvatarUrl: realMadrid,
    teamName: "Paide",
    num: "4",
    hasComment: true,
    member: "Ceesay",
  },
  {
    screenUrl: sixthImage,
    date: "02.08.24",
    teamAvatarUrl: realMadrid,
    teamName: "Vaprus",
    num: "4",
    hasComment: false,
    member: "Kask",
  },
  {
    screenUrl: seventhImage,
    date: "27.07.24",
    teamAvatarUrl: realMadrid,
    teamName: "Tammeka",
    num: "4",
    hasComment: false,
    member: "Epton",
  },
];

export const markTableData = [
  ["-1", "1.7", "2", "2", "0", "2"],
  ["2", "1.0", "-1", "-1", "-1", "-1"],
  ["2", "1.7", "2", "2", "2", ""],
  ["0", "0.7", "-1", "-1", "-1", "-1"],
  ["1", "1.7", "0", "1", "2", "2"],
  ["2", "1.7", "2", "2", "0", "2"],
  ["-1", "1.0", "0", "2", "-1", "-1"],
  ["-1", "0.7", "-1", "-1", "-1", "-1"],
  ["2", "1.7", "2", "", "", "2"],
  ["2", "1.7", "-1", "-1", "-1", "-1"],
  ["-1", "1.0", "-1", "-1", "-1", "-1"],
  ["-1", "1.7", "-1", "-1", "-1", "-1"],
  ["1", "0.7", "-1", "-1", "-1", "-1"],
  ["-1", "1.7", "0", "1", "2", "2"],
  ["2", "0.7", "-1", "-1", "-1", "-1"],
];
